version: '3'

services:
  # Redis Server
  redis:
    image: "docker.dragonflydb.io/dragonflydb/dragonfly" # dragonfly instead of redis
# # Activate the lines below if you want to expose Redis ports to other services
#    ports:
#      - "6379:6379"
#    restart: always

  # Python Application
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: always
